version: "3"
tasks:
  fmt:
    cmds:
      - go fmt ./...
  lint:
    cmds:
      - golangci-lint run
  build:
    cmds:
      - go build -o bin/app ./...
    deps:
      - fmt
      - lint
  test:
    cmds:
      - go test ./inner/...
    deps:
      - build
  it:
    cmds:
      - go test ./integration_tests/...
    deps:
      - build
  default:
    deps:
      - build